engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  shellcheck:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  nodesecurity:
    enabled: true
