language: ruby
rvm:
  - 2.1.5
addons:
  apt:
    packages:
    - nodejs
    - xvfb
cache:
- apt: true
- "$HOME/.electron"
- "$HOME/.rvm"
- "client/node_modules"
gemfile: server/Gemfile
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
  - cd client && npm install && cd -
  - cd server && bundle install && cd -