#
# Copyright (c) 2016 IMcPwn  - http://imcpwn.com
# BrowserBackdoorServer by IMcPwn.
# See the file 'LICENSE' for copying permission
#

source 'https://rubygems.org'

gem 'eventmachine'
gem 'em-websocket'
gem 'pry'
gem 'rb-readline'
gem 'colorize'
