#
# Copyright (c) 2016 Carleton Stuberg - http://imcpwn.com
# BrowserBackdoorServer by IMcPwn.
# See the file 'LICENSE' for copying permission
#

gem 'eventmachine'
gem 'em-websocket'

source 'https://rubygems.org'
